name: Workflows-Ruby
on: [push]

jobs:
  trabajo1:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install  --jobs 4 --retry 3
      
    - name: Setup database
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run tests
      run: |
        bin/rails test